/**
 * Framework-free markdown-it wikilink rendering and host integration contracts.
 *
 * @packageDocumentation
 */

import type MarkdownIt from "markdown-it";
import { escapeHtml, escapeHtmlAttribute } from "./escape.js";
import { createWikilinkHref } from "./url.js";

const WIKILINK_PATTERN = /^\[\[([^|\]\n]+)(\|([^\]\n]+))?\]\]/;
const SAFE_ATTRIBUTE_NAME_PATTERN = /^[^\s"'<>/=]+$/;
const URI_SCHEME_PATTERN = /^[A-Za-z][A-Za-z\d+.-]*:/;

/**
 * HTML attribute values accepted by the renderer.
 *
 * @public
 */
export type WikilinkHtmlAttributeValue =
  string | number | boolean | null | undefined;

/**
 * Immutable render context passed to host callbacks.
 *
 * @public
 */
export interface WikilinkRenderContext {
  /** Original target text from the left side of the wikilink. */
  readonly target: string;
  /** Escaped-output-independent visible label. */
  readonly label: string;
  /** Default destination produced by the core URL builder. */
  readonly defaultHref: string;
  /** Markdown-it render environment supplied by the host. */
  readonly env: unknown;
}

/**
 * Context passed to an app-owned tooltip renderer.
 *
 * @public
 */
export interface WikilinkTooltipRenderContext extends WikilinkRenderContext {
  /** Complete, escaped anchor HTML generated by the core plugin. */
  readonly anchorHtml: string;
  /** Raw tooltip returned by the host resolver. */
  readonly tooltip: string;
  /** Tooltip escaped for insertion as HTML text. */
  readonly escapedTooltip: string;
  /** Final destination after `resolveHref`. */
  readonly href: string;
}

/**
 * Configuration for the framework-free wikilinks plugin.
 *
 * @public
 */
export interface WikilinksOptions {
  /** Base used for absolute local links. */
  readonly baseURL?: string;
  /** Base used for relative local links. */
  readonly relativeBaseURL?: string;
  /** Force local links to use `baseURL`. */
  readonly makeAllLinksAbsolute?: boolean;
  /** Suffix appended to local page destinations. */
  readonly uriSuffix?: string;
  /** Static attributes added to every anchor; unsafe names and `href` are ignored. */
  readonly htmlAttributes?: Readonly<
    Record<string, WikilinkHtmlAttributeValue>
  >;
  /** Derive a page path for wikilinks without an explicit label. */
  readonly generatePagePathFromLabel?: (label: string) => string;
  /** Transform the local page path without touching query or fragment boundaries. */
  readonly postProcessPagePath?: (path: string) => string;
  /** Transform a heading fragment. */
  readonly postProcessPageHash?: (hash: string) => string;
  /** Transform the visible label. */
  readonly postProcessLabel?: (label: string) => string;
  /** Override the core destination synchronously. */
  readonly resolveHref?: (context: WikilinkRenderContext) => string;
  /** Resolve optional tooltip text synchronously. */
  readonly resolveTooltip?: (
    context: WikilinkRenderContext,
  ) => string | undefined;
  /** Render app-owned tooltip markup around the generated anchor. */
  readonly renderTooltip?: (context: WikilinkTooltipRenderContext) => string;
}

interface NormalizedOptions {
  readonly baseURL: string;
  readonly relativeBaseURL: string;
  readonly makeAllLinksAbsolute: boolean;
  readonly uriSuffix: string;
  readonly htmlAttributes: Readonly<Record<string, WikilinkHtmlAttributeValue>>;
  readonly generatePagePathFromLabel: (label: string) => string;
  readonly postProcessPagePath: (path: string) => string;
  readonly postProcessPageHash: (hash: string) => string;
  readonly postProcessLabel: (label: string) => string;
  readonly resolveHref:
    ((context: WikilinkRenderContext) => string) | undefined;
  readonly resolveTooltip:
    ((context: WikilinkRenderContext) => string | undefined) | undefined;
  readonly renderTooltip:
    ((context: WikilinkTooltipRenderContext) => string) | undefined;
}

interface WikilinkMeta {
  readonly target: string;
  readonly rawLabel: string;
  readonly hasExplicitLabel: boolean;
}

interface MarkdownTokenLike {
  markup: string;
  content: string;
  meta: unknown;
}

interface MarkdownInlineStateLike {
  pos: number;
  readonly posMax: number;
  readonly src: string;
  push(type: string, tag: string, nesting: -1 | 0 | 1): MarkdownTokenLike;
}

/**
 * Creates a markdown-it plugin that renders escaped, ordinary HTML anchors.
 *
 * The root entry performs no filesystem access and emits no framework-specific
 * components. Filesystem tooltip discovery belongs to the `./node` adapter.
 *
 * @public
 */
export default function wikilinks(
  options: WikilinksOptions = {},
): (md: MarkdownIt) => void {
  const normalizedOptions = normalizeOptions(options);

  return (md: MarkdownIt) => {
    md.inline.ruler.before("link", "wikilink", wikilinkInlineRule);
    md.renderer.rules.wikilink = (
      tokens,
      index,
      _markdownOptions,
      env: unknown,
    ) =>
      renderWikilink(
        tokens[index]?.meta as WikilinkMeta,
        normalizedOptions,
        env,
      );
  };
}

function wikilinkInlineRule(
  state: MarkdownInlineStateLike,
  silent: boolean,
): boolean {
  const start = state.pos;
  if (
    start + 3 >= state.posMax ||
    state.src.charCodeAt(start) !== 0x5b ||
    state.src.charCodeAt(start + 1) !== 0x5b
  ) {
    return false;
  }

  const match = WIKILINK_PATTERN.exec(state.src.slice(start));
  if (!match) {
    return false;
  }
  if (silent) {
    return true;
  }

  const token = state.push("wikilink", "", 0);
  token.markup = match[0];
  token.content = match[0];
  token.meta = Object.freeze({
    target: match[1] ?? "",
    rawLabel: match[3] ?? match[1] ?? "",
    hasExplicitLabel: match[3] !== undefined,
  } satisfies WikilinkMeta);
  state.pos += match[0].length;
  return true;
}

function normalizeOptions(options: WikilinksOptions): NormalizedOptions {
  return Object.freeze({
    baseURL: options.baseURL ?? "/",
    relativeBaseURL: options.relativeBaseURL ?? "./",
    makeAllLinksAbsolute: options.makeAllLinksAbsolute ?? false,
    uriSuffix: options.uriSuffix ?? ".html",
    htmlAttributes: Object.freeze({ ...(options.htmlAttributes ?? {}) }),
    generatePagePathFromLabel:
      options.generatePagePathFromLabel ?? ((label) => label),
    postProcessPagePath:
      options.postProcessPagePath ?? defaultPostProcessPagePath,
    postProcessPageHash:
      options.postProcessPageHash ??
      ((hash) => hash.trim().replace(/\s+/g, "_")),
    postProcessLabel: options.postProcessLabel ?? defaultPostProcessLabel,
    resolveHref: options.resolveHref,
    resolveTooltip: options.resolveTooltip,
    renderTooltip: options.renderTooltip,
  });
}

function renderWikilink(
  meta: WikilinkMeta,
  options: NormalizedOptions,
  env: unknown,
): string {
  const label = options.postProcessLabel(meta.rawLabel);
  const generatedTarget = meta.hasExplicitLabel
    ? meta.target
    : transformReferencePath(meta.target, options.generatePagePathFromLabel);
  const defaultHref = createWikilinkHref(generatedTarget, options);
  const initialContext = Object.freeze({
    target: meta.target,
    label,
    defaultHref,
    env,
  } satisfies WikilinkRenderContext);
  const href = options.resolveHref?.(initialContext) ?? defaultHref;
  const tooltip = options.resolveTooltip?.(initialContext)?.trim() ?? "";
  const hasCustomTitle = hasRenderableAttribute(
    "title",
    options.htmlAttributes,
  );
  const fallbackTitle = hasCustomTitle
    ? undefined
    : tooltip !== "" && options.renderTooltip === undefined
      ? tooltip
      : tooltip === ""
        ? label
        : undefined;
  const anchorHtml = `<a ${renderHtmlAttributes(href, options.htmlAttributes, fallbackTitle)}>${escapeHtml(label)}</a>`;

  if (tooltip === "" || options.renderTooltip === undefined) {
    return anchorHtml;
  }

  return options.renderTooltip(
    Object.freeze({
      ...initialContext,
      href,
      anchorHtml,
      tooltip,
      escapedTooltip: escapeHtml(tooltip),
    }),
  );
}

function defaultPostProcessLabel(label: string): string {
  const trimmed = label.trim();
  return trimmed.startsWith("#")
    ? trimmed.slice(1)
    : trimmed.replace(/#[^#]*$/, "");
}

function defaultPostProcessPagePath(pagePath: string): string {
  return pagePath
    .trim()
    .split("/")
    .map((segment) => {
      if (segment === "." || segment === "..") {
        return segment;
      }
      return segment.replace(/[\\<>:*|"]/g, "").replace(/\s+/g, "_");
    })
    .join("/");
}

function renderHtmlAttributes(
  href: string,
  attributes: Readonly<Record<string, WikilinkHtmlAttributeValue>>,
  fallbackTitle: string | undefined,
): string {
  const rendered = [`href="${escapeHtmlAttribute(href)}"`];
  for (const [name, value] of Object.entries(attributes)) {
    if (
      name.toLowerCase() === "href" ||
      !SAFE_ATTRIBUTE_NAME_PATTERN.test(name) ||
      value === null ||
      value === undefined
    ) {
      continue;
    }
    rendered.push(`${name}="${escapeHtmlAttribute(String(value))}"`);
  }
  if (fallbackTitle !== undefined) {
    rendered.push(`title="${escapeHtmlAttribute(fallbackTitle)}"`);
  }
  return rendered.join(" ");
}

function hasRenderableAttribute(
  name: string,
  attributes: Readonly<Record<string, WikilinkHtmlAttributeValue>>,
): boolean {
  const normalizedName = name.toLowerCase();
  return Object.entries(attributes).some(
    ([attributeName, value]) =>
      attributeName.toLowerCase() === normalizedName &&
      SAFE_ATTRIBUTE_NAME_PATTERN.test(attributeName) &&
      value !== null &&
      value !== undefined,
  );
}

function transformReferencePath(
  reference: string,
  transformPath: (path: string) => string,
): string {
  if (URI_SCHEME_PATTERN.test(reference.trim())) {
    return reference;
  }
  const hashIndex = reference.indexOf("#");
  const beforeHash =
    hashIndex === -1 ? reference : reference.slice(0, hashIndex);
  const fragment = hashIndex === -1 ? "" : reference.slice(hashIndex);
  const queryIndex = beforeHash.indexOf("?");
  const path = queryIndex === -1 ? beforeHash : beforeHash.slice(0, queryIndex);
  const query = queryIndex === -1 ? "" : beforeHash.slice(queryIndex);
  return `${path === "" ? "" : transformPath(path)}${query}${fragment}`;
}

export { createWikilinkHref } from "./url.js";
export type { CreateWikilinkHrefOptions } from "./url.js";
