name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    permissions:
      contents: read
      pull-requests: read
    uses: global-torque/.github/.github/workflows/public-package-ci.yml@aad63ce2f9587ed59117c89c1660b9d8a76ee7d3
