name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    permissions:
      contents: read
      pull-requests: read
    uses: global-torque/.github/.github/workflows/public-package-ci.yml@2d68cda919ed54b8d57d8b00b33381d75f237192
