name: CI

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

jobs:
  package:
    permissions:
      contents: read
      pull-requests: read
    uses: global-torque/.github/.github/workflows/public-package-ci.yml@ac9b50d639ad4e29fd6d4eba1d177ac96870d43f
